### ISSUE TITLE
No MQTT events for PUT-Requests?

### ISSUE THREAD

**Issue by de-ich** [eclipse-basyx/basyx-java-server-sdk#300] opened 2024-05-28 08:15 UTC
Hello,

I was testing the MQTT event feature of the submodel repository. When I update an existing Property via a PATCH request, it seems that no MQTT event is sent.

I used the following setup:

eclipsebasyx/aas-environment:2.0.0-SNAPSHOT

Best regards
Matthias

**Comment by mdanish98** [comment] 2024-05-29 07:23
Hi @de-ich ,

Thanks for raising this issue.
Would it be possible for you to share the configurations you used in this? like application.properties etc

**Comment by de-ich** [comment] 2024-05-29 07:55
See https://github.com/eclipse-basyx/basyx-java-server-sdk/issues/299#issuecomment-2136777055

**Comment by aaronzi** [comment] 2024-05-30 09:23
Hello @de-ich,

I can't reproduce that issue. I also have to say I'm a bit confused. In #299 you say that updating Properties works fine. Properties are updated via PATCH in the AAS Web UI. I also verified that this works and triggers an MQTT event. Could you please clarify what the issue is here?

**Comment by de-ich** [comment] 2024-06-17 13:19
Hello @aaronzi,

you are right - I labeled one of my requests incorrectly and got confused. The problem does not seem to be with PATCH requests but with PUT requests:

When I update a Property (value) with a PATCH request, an MQTT event is generated correctly. However, when I replace the complete property with a PUT request, no MQTT event is generated.

**Comment by aaronzi** [comment] 2024-06-18 05:55
Alright ;)
We will have another look at this.

**Comment by aaronzi** [comment] 2024-06-25 08:43
Update: This is a Bug. We are currently missing one line of code that should have been there for this feature to work. We will create a PR for this immediately.

**Comment by aaronzi** [comment] 2024-07-05 13:15
The PR is merged now

**Closed by aaronzi** 2024-07-05 13:15 UTC
