### ISSUE TITLE
InMemory variant looses SubmodelElements

### ISSUE THREAD

**Issue by lenaxus** [eclipse-basyx/basyx-java-server-sdk#85] opened 2023-08-30 07:11 UTC
We setup the Basyx Environment with the configuration `basyx.backend=InMemory` to use and test the basyx environment locally.

We did following steps to enter data in the repository:
- POST an AAS with the endpoint `/shells`
- POST a submodel with the endpoint `/submodels`
- POST a submodelRef to the existing AAS with the endpoint `/shells/{aasIdentifier}/submodel-refs`
- If we than access this submodel with the endpoint `/submodels/{submodelIdentifier}` it all looks good and we see the corresponding submodelElements
- But if we then get the MetaData of this submodel with the endpoint `/submodels/{submodelIdentifier}/$metadata`, the result of this request is right and we see the MetaData of this submodel
- But after that MetaData call if we do again the request to see the submodel with the endpoint `/submodels/{submodelIdentifier}`, the submodel itself looks good but the submodelElements key is not there anymore

So it seems that here is a bug when calling the MetaData of submodel endpoint it then deletes the corresponding submodelElements of this submodel.

**Comment by mhrimaz** [comment] 2023-08-30 09:59
@lenaxus You are right.
the root cause is on [this line probably.](https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/1222ae286ab7dd62e40df164e83f5c78fa585a31/basyx.submodelrepository/basyx.submodelrepository-backend-inmemory/src/main/java/org/eclipse/digitaltwin/basyx/submodelrepository/InMemorySubmodelRepository.java#L223)
@FrankSchnicke Maybe a deep copy and then removing the extra `submodelelements` would be a quick fix. I can try to fix it if no one is going to do.

**Comment by mhrimaz** [comment] 2023-08-30 10:25
However, what would be suggestion for deep cloning? AAS4j doesn't offer any copy constructor, nor override clone method. Which I think there should be such feature, when mutation is allowed and the structure is so complex. It will be hard to keep track of these mutations.
So now the easy approach would be to serialize to json, and get back a new object again, which is not the most efficient way.

**Comment by FrankSchnicke** [comment] 2023-09-04 12:50
Thank you very much for pointing out this issue. 

@mhrimaz : Currently the only way of creating a deep copy is serialization and deserialization, e.g., to JSON. However, we're planning on adding a deep copy function to AAS4J. Would you like to raise a PR? Otherwise, we will take a look at this and fix it.

**Comment by mhrimaz** [comment] 2023-09-05 06:26
@FrankSchnicke you can assign it to me, I will raise a PR.

**Comment by FrankSchnicke** [comment] 2023-09-27 06:17
@mhrimaz are you still interested in doing this PR? If yes, can you estimate until when the PR will be available?

**Comment by mhrimaz** [comment] 2023-09-27 08:43
@FrankSchnicke Yes.
Submodel to Json serialization was clear, but I am looking for a way to serialize json to Submodel. (for deep cloning)
If you have a hint here, I appreciate it, otherwise, I have to look in other places in the code to find a way for it.

**Comment by FrankSchnicke** [comment] 2023-09-27 08:46
You can use the [readReferable](https://github.com/eclipse-aas4j/aas4j/blob/1720fa638897361879dd1efb480ac5d6701c51c9/dataformat-json/src/main/java/org/eclipse/digitaltwin/aas4j/v3/dataformat/json/JsonDeserializer.java#L198) method of AAS4J for this.

**Comment by mhrimaz** [comment] 2023-09-27 08:53
Exactly tried that:

`Submodel submodelDeepCopy = new JsonDeserializer().readReferable(submodelAsJSON, Submodel.class);`

but getting an error:

`com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve subtype of [simple type, class org.eclipse.digitaltwin.aas4j.v3.model.SubmodelElement]: missing type id property 'modelType' (for POJO property 'submodelElements')`

However, I am pretty sure my payload is correct, but I have to debug it further to spot the problem.

**Comment by FrankSchnicke** [comment] 2023-10-04 09:16
The issue is fixed and a new SNAPSHOT version was uploaded to DockerHub. Thanks again for pointing this out!

**Closed by FrankSchnicke** 2023-10-04 09:16 UTC
